collections:
  dogs:
    output: true
defaults:
  - scope:
      path: ""
      type: "dogs"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-remote-theme # add this line to the plugins list if you already have one
  - jekyll-include-cache
lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "aqua" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
title: "Fuckoff Tardo"
subtitle: "Nuttin to see here"
url: "https://gh.benstrawbridge.com"
repository: "benstraw/benstraw.github.io"
breadcrumbs: true