collections:
  dogs:
    output: true
defaults:
  - scope:
      path: ""
      type: "dogs"
    values:
      layout: "dog"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
gh_pat: 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  